test_add (test_szys.TestSzYs) ... ok
test_sub (test_szys.TestSzYs) ... ok
test_multi (test_szys.TestSzYs) ... ok
test_divide (test_szys.TestSzYs) ... FAIL

======================================================================
FAIL: test_divide (test_szys.TestSzYs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\陈莉\Desktop\大三下\软件工程\test_szys.py", line 25, in test_divide
    self.assertEqual(3, divide(7, 2))
AssertionError: 3 != 3.5

----------------------------------------------------------------------
Ran 4 tests in 0.004s

FAILED (failures=1)
